"""Write a function mutate to compute all words generated by a single mutation on a given word. A mutation is defined as inserting a character, deleting a character,
 replacing a character, or swapping 2 consecutive characters in a string. 
For simplicity consider only letters from a to z."""

def mutate(word):
	output_list = []
	letters = map(chr, xrange(97,123))
	
	for x in xrange(len(word)):
		for y in xrange(26):
			output_list.append(word[:x] + letters[y] + word[x:])


	for x in xrange(len(word)):
		output_list.append(word[:x] + word[x+ 1:])

	for x in xrange(len(word)):
		for y in xrange(26):
			output_list.append(word[:x] + letters[y] + word[x+1:])

	return output_list


print "helo" in mutate("hello")
